### PR TITLE
Adds missing headers to the module map

### PR DESCRIPTION
**Pull request by danthorpe**
These changes fixes the warnings that appear when importing YapDatabase as a module.

However, one of them is `YapDatabaseSearchQueuePrivate.h` which doesn't sounds as though it should be made public. So, possibly there needs to be an audit of the access levels for this header? It is imported by `YapDatabaseSearchResultsViewTransaction.m`. @robbiehanson this is probably something for you to look into, as something doesn't seem correct.

### CODE REVIEW

**Comment by jj0b** [comment]
For anyone that wants to avoid these warnings before the pod is updated to integrate this change, you can use `pod 'YapDatabase', :git => 'https://github.com/yapstudios/YapDatabase'` in your podfile to use the latest on master.

**Comment by robbiehanson** [comment]
The podspec for v2.7.3 has now been pushed.

**Comment by jj0b** [comment]
@robbiehanson now that you have removed the YapDatabaseSearchQueuePrivate header from the modulemap is there another way to fix the Umbrella header warning for this or do we just have to live with the warning? I'm also seeing this warning for YapMutationStack but it isn't clear to me if that should or shouldn't be in the modulemap file.

**Comment by robbiehanson** [comment]
> do we just have to live with the warning?

No, definitely not. Let's fix it. I just don't understand where the warning is coming from. (I thought I had fixed this with an earlier change, but it looks like I was wrong.)

> it isn't clear to me if that should or shouldn't be in the modulemap file.

Since YapDatabaseSearchQueuePrivate.h is private, it's not designed to be exposed. I'd rather get to the bottom of the reason why we're seeing this problem. But if we're all stumped, we can just put it back in the modulemap for now.

**Pull request merged**
