### PR TITLE
Add a RTreeIndex extension

### PR DESCRIPTION
**Pull request by maelp**
Two questions remain:
- not sure if we need `YapDatabaseRTreeIndexCache`
- not sure how to choose the enum constants in `YapDatabaseRTreeIndexHandler`

### CODE REVIEW

**Comment by maelp** [comment]
Tell me if you need more info on how it goes behind. FYI I included it in my work (check <https://github.com/snipsco/Sqlite3WithExtensions> for a build of sqlite3 with R-tree and <https://github.com/snipsco/YapDatabaseFramework> for a framework to use YapDatabase in Swift) and it is fine.

An issue I have though is it seems when I add a point, eg minLon == maxLon & minLat == maxLat, when I look at the .sqlite db using `sqlitebrower`, the stored coordinates are slightly different for minLon and maxLon, and minLat and maxLat. Not sure if this is sqlite using eg. float instead of double, and if this can be changed by a compiler flag

image

The difference seems to be in the order of 1e-7 which for lonlat coordinates amount to around 1cm, so it is no big deal, but just a bit strange that it does not store the coordinates with the same precision

**Comment by chrisballinger** [comment]
@maelp Awesome work! I can contribute an R-Tree subspec if needed because it appears to be a very similar process to how I made the SQLCipher one.

As far as the precision issue, the [rtree docs say](https://www.sqlite.org/rtree.html) "By default, coordinates are stored in an R*Tree using 32-bit floating point values." so I'm guessing that's what you're seeing.

Do you have any example code or tests you can share?

**Comment by maelp** [comment]
Indeed

> By default, coordinates are stored in an R*Tree using 32-bit floating point values. When a coordinate cannot be exactly represented by a 32-bit floating point number, the lower-bound coordinates are rounded down and the upper-bound coordinates are rounded up. Thus, bounding boxes might be slightly larger than specified, but will never be any smaller. This is exactly what is desired for doing the more common "overlapping" queries where the application wants to find every entry in the R*Tree that overlaps a query bounding box. Rounding the entry bounding boxes outward might cause a few extra entries to appears in an overlapping query if the edge of the entry bounding box corresponds to an edge of the query bounding box. But the overlapping query will never miss a valid table entry.

Sure for the subspec!
Here is an example of code: <https://gist.github.com/maelp/06f621741acf70390252> you might need to add this to a workspace with <https://github.com/snipsco/Sqlite3WithExtensions> and <https://github.com/snipsco/YapDatabaseFramework> included, where in YapDatabaseFramework you need to checkout the `rtree-extension` branch of <https://github.com/snipsco/YapDatabase>

Not sure what is the easiest way to share this code, we are experimenting with Carthage for our builds and there are a few rough edges still

**Comment by maelp** [comment]
Added this as a comment in the code, we should add this to documentation :)

**Comment by robbiehanson** [comment]
Awesome !

**Comment by robbiehanson** [comment]
> Two questions remain:
> • not sure if we need YapDatabaseRTreeIndexCache

The queryCache just helps to reduce the overhead of always compiling the sql queries. For once-off queries, it's not helpful. But in situations where the user is constantly running the same query over and over again, we get a small benefit from it.

> • not sure how to choose the enum constants in YapDatabaseRTreeIndexHandler

Looks like you did it perfectly.

Back in the day I did them all the same way (1, 2, 3, 4). Like this:

```objective-c
typedef NS_ENUM(NSInteger, YapDatabaseViewBlockType) {
	YapDatabaseViewBlockTypeWithKey       = 1,
	YapDatabaseViewBlockTypeWithObject    = 2,
	YapDatabaseViewBlockTypeWithMetadata  = 3,
	YapDatabaseViewBlockTypeWithRow       = 4
};
```

But then one day I passed a YapDatabaseViewBlockTypeX to a method that was expecting YapDatabaseSecondaryIndexBlockType. And it worked. And the compiler didn't complain.

This prompted me to start using different values for each class. However, it's probably a moot point now because of NS_ENUM and a bunch of compiler improvements. In fact, we could probably drop the explicit values from all of these today.

**Comment by maelp** [comment]
Thanks! I think the only missing things are documentation on:
 - how to build sqlite3 with R-Tree support (you can check <https://github.com/snipsco/Sqlite3WithExtensions> for an example)
 - how to index items in the R-Tree (I gave an example at <https://gist.github.com/maelp/06f621741acf70390252>)
 - documentation (there is some in the code, but we can update the wiki)
 - unit tests

**Pull request merged**
