### PR TITLE
Add missing foundation import

### PR DESCRIPTION
**Pull request by wjmelements**
#### Changes
This missing import is required to build with BUCK
Reviewers @robbiehanson

### CODE REVIEW

**Comment by mickeyl** [comment]
Foundation is a builtin framework, hence it would be more appropriate to import it like that:

`#import <Foundation/Foundation.h>`

**Comment by wjmelements** [comment]
@robbiehanson ptal

**Comment by wjmelements** [comment]
@robbiehanson ptal

**Comment by wjmelements** [comment]
For anyone else that may be having this issue, I have created a pod based on this branch. To use it:
```
pod 'YapDatabase/SQLCipher', :git => 'git@github.com:wjmelements/YapDatabase.git', :tag => '3.1.1'
```

**Comment by robbiehanson** [comment]
I will push a new version (v3.1.1) soon. In the meantime, if this affects anyone you can directly reference the commit:

```
pod 'YapDatabase/SQLCipher', :git=>'https://github.com/yapstudios/YapDatabase.git', :commit=>'e8c4021aa1967e54451376f0c1c3d33dfe434606'
```

**Comment by robbiehanson** [comment]
@wjmelements Thank you !

**Comment by robbiehanson** [comment]
v3.1.1 has been pushed to CocoaPods

**Pull request merged**
