### PR TITLE
[YAP-244]: Adds nullable attribute to properties consistently.

### PR DESCRIPTION
**Pull request by danthorpe**
There were more `nullable` attributes missing from properties which should be optionals. Also, I've edited existing `nullable` attributes so that they're added to the list of property attributes so that nullable is added consistently at the end.

### CODE REVIEW

**Comment by robbiehanson** [comment]
> nullable is added consistently at the end.

Consistency is appreciated. I'll keep this ordering in mind.

**Comment by danthorpe** [comment]
:+1:

**Comment by danthorpe** [comment]
@robbiehanson is there any chance that recent changes which fix build issues in Carthage & the missing nullable attributes can be released as 2.7.5?

**Comment by robbiehanson** [comment]
v2.7.5 has been tagged & pushed.

**Comment by danthorpe** [comment]
Thanks @robbiehanson

**Comment by danthorpe** [comment]
@robbiehanson would you also be able to push it to CocoaPods? Thanks!

**Comment by robbiehanson** [comment]
I did: https://cocoapods.org/?q=YapDatabase

**Comment by danthorpe** [comment]
Oh - sorry - weird `$ pod search YapDatabase` isn't showing it. I thought it would pull the search results right off the site.

**Comment by robbiehanson** [comment]
Heads-up. I had to push v2.7.6 because of issue #245

**Pull request merged**
