### PR TITLE
Add Xcode project with dynamic framework target

### PR DESCRIPTION
**Pull request by dhardiman**
I'd like to use YapDatabase without cocoa pods, so I've added an Xcode project with a dynamic framework target, which could be used for Carthage etc. I'm incredibly new to YapDatabase, so don't know whether the module is really as tidy as it could/should be. I've just copied the output from building with cocoa pods with `use_frameworks!`. Happy to tidy this up as required, with explicit modules or whatever so others can use this as well. Also I imagine it might be preferable for this to be on one of the other Xcode projects within the repo, but thought I'd start here as a quick solution.

### CODE REVIEW

**Comment by danthorpe** [comment]
:+1:  @robbiehanson - is there an issue with this PR which can be addressed?

**Comment by robbiehanson** [comment]
> is there an issue with this PR stopping it being merged

@danthorpe Nope. Just my busy schedule. Merged now.

**Comment by danthorpe** [comment]
Thanks @robbiehanson :+1:

**Comment by dhardiman** [comment]
Thanks @robbiehanson . Let me know if you need any further changes to it. Happy to make them.

**Pull request merged**
