### PR TITLE
Added dst_name index to relationship table

### PR DESCRIPTION
**Pull request by ksuther**
This dramatically speeds up enumerating edges with enumerateEdgesWithName:destinationKey:collection:usingBlock:.

Without this index it would use the name index and then have to scan through the remaining results (sqlite can only use one index per table, see http://www.sqlite.org/optoverview.html). This isn't better than a linear scan in cases where most of the rows in the database all have the same name.

It may also be good to have a src_name index added as well. I don't ever enumerate edges by sourceKey so I don't know if it's worth the overhead to have this index as well.

### CODE REVIEW

**Comment by ksuther** [comment]
As an alternative to adding another index for dst_name or src_name, enumerateForSrcNameStatement could be changed to specify the index to use (https://sqlite.org/lang_indexedby.html). So

`SELECT "rowid", "dst", "rules", "manual" FROM "%@" WHERE "src" = ? AND "name" = ?;`

would become:

`SELECT "rowid", "dst", "rules", "manual" FROM "%@" INDEXED BY src WHERE "src" = ? AND "name" = ?;`

This will ensure the optimizer doesn't use the name index, which is less specific. The overhead for a compound index is pretty small, so adding the index is probably better.

**Comment by ksuther** [comment]
Any feedback on this? I'm happy to do a bit more legwork to make this ready for a merge if necessary. We've been shipping with this extra index added and it's fixed some edge case performance issues for us.

**Comment by robbiehanson** [comment]
Instead of a new "dst_name" and "src_name" index, what if we simply changed the existing "dst" index to a "dst_name" compound index. And also changed the existing "src" index to a "src_name" compound index.

If I understand correctly, SQLite can use a "dst_name" index even when it's only interested in the dst.

**Comment by ksuther** [comment]
Yeah, that would work as well. Looks like a compound index works just as well as a single column index as long as it's checking the first column in the index.

**Comment by robbiehanson** [comment]
I'm also thinking we can drop the individual "name" index. In terms of usage, the most common queries should be:

1. src = ? AND name = ?
2. dst = ? AND name = ?
3. src = ? OR dst = ?

Where 1 & 2 occur whenever the user want to enumerate edges from a particular src or dst. And 3 occurs whenever a row is deleted from the database (and sqlite's OR-clause optimization can save us here).

I cannot think of common cases where a user would enumerate based solely on the name. Which means this index is likely just taking up space. Thoughts ?

**Comment by ksuther** [comment]
I don't know if `enumerateEdgesWithName:usingBlock:` is used frequently out in the wild, I don't use it. If someone has a bunch of different edge types and then tries to enumerate an edge name that's a small percentage of the total edges, that'll result in unexpectedly slow queries. If the name index does get removed, then adding a warning to `enumerateEdgesWithName:usingBlock:` would reduce the potential for surprises.

**Comment by robbiehanson** [comment]
@ksuther giving you a heads up concerning changes to YapDatabaseRelationship extension in v2.8:

- it now uses "src_name" & "dst_name" indexes, so you should continue to see the performance improvement you had in your custom version
- it now has an internal cache for "clean" edges, so this should be a small performance improvement (it can skip certain steps like looking up sourceKey/sourceCollection from sourceRowid often)
- it now uses NSURL (instead of NSString) to store destination file references.

The tricky part for you is that both v2.8 and your custom branch have YAP_DATABASE_RELATIONSHIP_CLASS_VERSION set to 4. So something may need to be whipped up to ensure everything works correctly.

Let me know if you have any questions.

**Comment by ksuther** [comment]
Awesome, thanks!

**Pull request closed without merging**
