### PR TITLE
Clear out the WAL when the database is configured on startup.

### PR DESCRIPTION
**Pull request by vickeryj**
This handles the mysterious case of a WAL that grows across app launches.

### CODE REVIEW

**Comment by robbiehanson** [comment]
I don't think this is correct. Or, at a minimum, the best way to handle this.

> "the mysterious case of a WAL that grows across app launches."
> "WALs that grow across app launches have been found in the field."

I'm not entirely sure what is meant by this. I suppose it must mean one of the following:
1. The WAL size at app launch X is greater than the WAL size at app launch X-1
2. The WAL size at app launch X >= X-1 >= X-2 >= X-3 ...

Number 1 is not necessarily a problem. Basically the WAL will grow and grow until all connections get caught up. And then, at that point, all frames in the WAL will be synced into the database file itself. Meaning that the next read-write transaction should reset the WAL file (rather than appending to it).

Number 2 is a problem. Likely a serious problem. Because it means one of two things:
- There's a rogue connection somewhere that is using a longLivedReadTransaction (and not listening for notifications, and moving forward to the latest commit) and thus preventing the WAL from being able to get reset
- There's some other bug, possibly in YapDatabase itself

And both of those are bad. I believe that addressing this bug as the pull request does is treating the symptom, and not the problem.

The good news is that there are existing tools in YapDatabase to help monitor the WAL size. You can turn on existing logging that will tell you:
- When YapDatabase is performing a checkpoint
- What snapshot number it thinks it can checkpoint up to
- How big the WAL file is before & after each checkpoint

Take a look at [YapDatabase asyncCheckpoint], and turn on PRINT_WAL_SIZE and verbose logging. Let me know what you find.

**Comment by vickeryj** [comment]
The case we are running into is #2. Launching the app does not result in the WAL being reduced to zero during the first call to `asyncCheckpoint:`. I'll create a separate issue with the logging output for that as I agree that it's most certainly a bug somewhere.

The point of this PR is to address the symptom, since it causes rather great pain when it occurs, requiring the app to be deleted and re-installed.

**Comment by robbiehanson** [comment]
> Launching the app does not result in the WAL being reduced to zero during the first call to asyncCheckpoint:

After the first call to asyncCheckpoint, it should be the next read-write transaction that ultimately resets the WAL size.

Meaning: If one opens the database, does a bunch of writes all at the same time (and then doesn't do any more writes after that) and then quits the app, the WAL file will continue to grow.

**Comment by robbiehanson** [comment]
Interestingly, sqlite added a SQLITE_CHECKPOINT_TRUNCATE option in v3.8.8
http://www.sqlite.org/changes.html

**Comment by stepanhruda** [comment]
I think the problem we are running into (I have some context on this) might be that frames in a WAL from a previous run aren't getting processed (even when we keep the database open after the first write).

We have an example WAL file with approx. 200k frames that aren't present in sqlite. The existence of it is most likely a result of a rogue long-lived connection, but that's not important. When we re-launch the app, it only processes as many frames as the new session made writes. Is that possible?

**Comment by robbiehanson** [comment]
Could you try the latest master ? I believe I fixed this issue via commit 54bfb0a51b76ce0e26267d151ca8530ba157b5e1

Take a look at the new YapDatabaseOptions.aggressiveWALTruncationSize property.

**Pull request closed without merging**
