### PR TITLE
Removed "-weak_library /usr/lib/libc++.dylib" from podspec.

### PR DESCRIPTION
**Pull request by skeeet**
Should solve bitcode conflict. #180

### CODE REVIEW

**Comment by chrisballinger** [comment]
Fails to link (check Travis results)

You'll need to add

`s.libraries = 'c++'`
`

**Comment by skeeet** [comment]
Yup, you right. Was testing on separate projects which links against libc++ and missed that.

**Comment by robbiehanson** [comment]
Thanks guys

**Comment by skeeet** [comment]
You welcome, Thanks for awesome library!

**Pull request merged**
