### PR TITLE
Fixes the xcode project

### LINKED ISSUE #495: Xcode project doesn't build due to files not being included in project
The Xcode project no longer builds due to several files not being included in the project

Files in question:
* YapDatabaseTypes.h
* YapDatabaseConnectionProxy.h/m
* YapDatabaseConnectionPool.h/m
* YapDatabaseCollectionConfig.h/m
* YapDatabaseConnectionConfig.h/m
* YDBLogMessage.h/m
* YapDatabaseLogging.m doesn't exist, but is in the compile sources build phase

### PR DESCRIPTION
**Pull request by gcox**
Resolves #495

### CODE REVIEW

**Comment by gcox** [comment]
@robbiehanson I tried including all the "Swift" folders within the "Extensions" folder, but doing so prevents compilation since the types extended in those swift files are not imported by the umbrella header. You can get past that by importing `YapDatabase.[appropriate explicit module]` in each of those swift files. That allows the frameworks to compile, but prevents compilation of the `TestModuleMap-*` targets due to this business: 

Screen Shot 2019-12-06 at 10 53 06 AM

One solution is to just split the framework up into Objective-C and Swift specific frameworks: YapDatabase, YapDatabaseSwift. `YapDatabaseSwift` would then depend on `YapDatabase`. A hard separation of Swift/Objective-C may also make supporting SPM easier, which was proving to be difficult in #498.

Any thoughts on all that?

**Comment by robbiehanson** [comment]
Unfortunately I cannot merge this PR in it's current state because the following files were moved, and thus broke the CocoaPods installation:

- YapDatabase/{Utilities => Extensions/ConnectionPool}/YapDatabaseConnectionPool.h
- YapDatabase/{Utilities => Extensions/ConnectionPool}/YapDatabaseConnectionPool.m
- YapDatabase/{Utilities => Extensions/ConnectionProxy}/YapDatabaseConnectionProxy.h
- YapDatabase/{Utilities => Extensions/ConnectionProxy}/YapDatabaseConnectionProxy.m

These files are no longer extensions. They are considered simple utility classes, and are now considered part of the core project.

**Comment by gcox** [comment]
I'll get that fixed shortly

**Comment by robbiehanson** [comment]
Thank you!

**Pull request merged**
