### PR TITLE
Upgrade CocoaLumberjack to 2.x

### PR DESCRIPTION
**Pull request by ir-fuel**

### CODE REVIEW

**Comment by leafduo** [comment]
Hope this get merged since we are using CocoaLumberjack 2.0

**Comment by robbiehanson** [comment]
I started working on the merge the other day. It's in a branch currently. I just need to go through and fix all the Xcode projects.

**Comment by robbiehanson** [comment]
I started working on the merge the other day. It's in a branch named "ir-fuel-master", which I pushed. Before merging into master, we just need to go through and fix the Xcode projects.

**Comment by aidenluo177** [comment]
Hope this get merged!

**Comment by robbiehanson** [comment]
CocoaLumberjack v2.x is now used in the 2.7 branch of YapDatabase.

**Pull request closed without merging**
