### PR TITLE
Xcode 9 warnings

### PR DESCRIPTION
**Pull request by adamwulf**
Small changes to silence build warnings in Xcode 9

### CODE REVIEW

**Comment by robbiehanson** [comment]
Thank you.

**Comment by mergesort** [comment]
Any chance this could be pushed to CocoaPods in a minor release, to get the benefits of this?

Thanks! 🙂

**Comment by robbiehanson** [comment]
@mergesort Good idea. Working on it now.

**Comment by robbiehanson** [comment]
@mergesort Pushed v3.0.2: https://cocoapods.org/pods/YapDatabase

**Comment by mergesort** [comment]
Awesome, thanks a lot!

**Pull request merged**
